baseurl         = "https://zacharybrounstein.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Zachary Brounstein"
  subtitle    = "My personal website"
  copyright   = "© 2019"

  cover       = "img/inner_pulse_space_cloud.jpg"
  description = "Zachary Brounstein"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

#  twitterName = "faketryghost"
#  fbName = "fakeghost"
#  githubName = "eueung"
  linkedinName = "zacharybrounstein"
  mediumName = ""

  logo = "Portrait.jpg"
#  orgName = "ZRB"
#  orgWebsite = "https://www.telematika.org"
#  orgDescription = "Here is a description placeholder for your org"

  showSupport = true

  author = "ZRB"
  authorAvatar = "Portrait.jpg"
  authorLocation = "Los Alamos, NM"
  authorWebsite = "https://zacharybrounstein.com/"
  authorDescription = "Scientist, Composer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 100
  
[[menu.main]]
  name = "Paintings"
  url = "/categories/"
  weight = 90
  
#[[menu.main]]
#  name = "Music"
#  url = "/categories/"
#  weight = 80

#[[menu.main]]
#  name = "Paintings"
#  url = "/tags/golang/"
#  weight = 100



#[[menu.main]]
#  name = "External"
#  url = "https://google.com/"
#  weight = 95